run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 2
  tests: false
  modules-download-mode: vendor
  allow-parallel-runners: true
  skip-dirs:
    - vendor

linters:
   disable-all: true
   enable:
    - errcheck
    # - exportloopref
    # - depguard
    # - gocritic
    # - gofumpt
    - goimports
    # - revive
    # - gosimple
    # - govet
    # - ineffassign
    - lll
    # - misspell
    # - staticcheck
    - stylecheck
    # - typecheck
    # - unconvert
    # - unparam
    # - unused
    # - gci
   fast: false

linters-settings:
  lll:
    line-length: 120
    tab-width: 4
