version: '3.8'

services:
  db:
    restart: always
    image: postgres:latest
    volumes:
    - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=todushka
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 6432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pg_data:

